### ISSUE TITLE
使用appveyor集成时总是编译失败

### ISSUE THREAD

**Issue by lvSally** [lvSally/lvSally.github.io.source#1]
ERROR Local hexo not found in C:\projects\lvsally-github-io-source
ERROR Try running: 'npm install hexo --save'

**Comment by lvSally** [comment]
将报错信息贴在Google上，果然有人遇到类似的问题，按照别人解决的尝试了好多次，都没有成功...
无意间看到build文件的warn信息，告诉我需要使用高版本的node，然后查appveyor文档修改稿node和npm版本成功解决。
```
environment:
  nodejs_version: "8"
  access_token:
    secure: uF55+RbWABidM1Irre7ZRkC9NLv6OxK2BgLZKzZXczF2slpkHabccD1JlKL7h0ZQ

install:
  - ps: Install-Product node $env:nodejs_version
  - npm -g install npm@next
  - node --version
  - npm --version
  - rm -rf node_modules/ && npm install
  - npm install hexo-cli -g

build_script:
  - hexo clean
  - hexo generate
```
很多时候我们只关注了`error`，有时候还是需要来接下`warn`信息的
